# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('core', 'core'),
        ('modules', 'modules'),
        ('assets', 'assets'),
    ],
    hiddenimports=[
        'core',
        'core.ui',
        'core.ui.app_window',
        'core.ui.tab_manager',
        'core.ui.modern_theme',
        'core.config',
        'core.config.settings',
        'core.config.user_settings',
        'core.config.preferences',
        'core.utils',
        'core.utils.logging',
        'core.utils.helpers',
        'core.utils.enhanced_helpers',
        'core.utils.errors',
        'core.utils.error_handling',
        'modules',
        'modules.screenshots',
        'modules.screenshots.ui',
        'modules.screenshots.logic',
        'modules.build_packager',
        'modules.build_packager.ui',
        'modules.build_packager.logic',
        'modules.docs_generator',
        'modules.docs_generator.ui',
        'modules.docs_generator.logic',
        'modules.ai_packager',
        'modules.ai_packager.ui',
        'modules.ai_packager.logic',
        'modules.release_creator',
        'modules.release_creator.ui',
        'modules.release_creator.logic',
        'modules.llm_assistant',
        'modules.llm_assistant.ui',
        'modules.llm_assistant.logic',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'pyautogui',
        'keyboard',
        'requests',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.simpledialog',
        'tkinter.colorchooser',
        'tkinter.ttk',
        'psutil',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ShipStudio',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    icon='assets/ship_studio.ico',
    target_arch=None,
    codesign_identity=None,  # You can set this to your certificate thumbprint
    entitlements_file=None,
)
